# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitaur < Formula
  desc "A simple git utility CLI tool"
  homepage "https://github.com/Exceptionate/gitaur"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/exceptionate/gitaur/releases/download/v0.1.2/gitaur-darwin-amd64.tar.gz"
      sha256 "b085a9f0ab02680fb391612756196d87afd17e8587480508130b83bb2f2e0df5"

      define_method(:install) do
        if OS.mac? && Hardware::CPU.arm?
          bin.install "gitaur-darwin-arm64" => "gitaur"
        elsif OS.mac? && Hardware::CPU.intel?
          bin.install "gitaur-darwin-amd64" => "gitaur"
        else
          bin.install "gitaur"
        fi
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/exceptionate/gitaur/releases/download/v0.1.2/gitaur-darwin-arm64.tar.gz"
      sha256 "8ef952644a9c8f4957709cf4051a2fd250768f7080197d907640d6efa9377581"

      define_method(:install) do
        if OS.mac? && Hardware::CPU.arm?
          bin.install "gitaur-darwin-arm64" => "gitaur"
        elsif OS.mac? && Hardware::CPU.intel?
          bin.install "gitaur-darwin-amd64" => "gitaur"
        else
          bin.install "gitaur"
        fi
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/exceptionate/gitaur/releases/download/v0.1.2/gitaur-linux-amd64.tar.gz"
      sha256 "507b880a959eb0db4dd5eb417aa8bd8f401dfc4ed9671de0492cd600eb1b630d"
      define_method(:install) do
        if OS.mac? && Hardware::CPU.arm?
          bin.install "gitaur-darwin-arm64" => "gitaur"
        elsif OS.mac? && Hardware::CPU.intel?
          bin.install "gitaur-darwin-amd64" => "gitaur"
        else
          bin.install "gitaur"
        fi
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/exceptionate/gitaur/releases/download/v0.1.2/gitaur-linux-arm64.tar.gz"
      sha256 "5d10ea6d942e99938411937f0c1f04d94f42199e3ec373ea78d9b9000870bd18"
      define_method(:install) do
        if OS.mac? && Hardware::CPU.arm?
          bin.install "gitaur-darwin-arm64" => "gitaur"
        elsif OS.mac? && Hardware::CPU.intel?
          bin.install "gitaur-darwin-amd64" => "gitaur"
        else
          bin.install "gitaur"
        fi
      end
    end
  end
end
