# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitaur < Formula
  desc "A simple git utility CLI tool"
  homepage "https://github.com/Exceptionate/gitaur"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/exceptionate/gitaur/releases/download/v0.1.2/gitaur-darwin-amd64.tar.gz"
      sha256 "5cfca73fcb659646ae67387c27bff2b2e19b5a847e421b50a10e8ba2d4bb8bc1"

      define_method(:install) do
        if OS.mac? && Hardware::CPU.arm?
          bin.install "gitaur-darwin-arm64" => "gitaur"
        elsif OS.mac? && Hardware::CPU.intel?
          bin.install "gitaur-darwin-amd64" => "gitaur"
        else
          bin.install "gitaur"
        fi
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/exceptionate/gitaur/releases/download/v0.1.2/gitaur-darwin-arm64.tar.gz"
      sha256 "b282dd3f3fb15c5a9d13bbb24a44f863b8a11e358edfc919259126a8e0cf9f91"

      define_method(:install) do
        if OS.mac? && Hardware::CPU.arm?
          bin.install "gitaur-darwin-arm64" => "gitaur"
        elsif OS.mac? && Hardware::CPU.intel?
          bin.install "gitaur-darwin-amd64" => "gitaur"
        else
          bin.install "gitaur"
        fi
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/exceptionate/gitaur/releases/download/v0.1.2/gitaur-linux-amd64.tar.gz"
      sha256 "47a1418bc70fc7ad6a5c73ae492051c522065d836c454cfd6e0dc19f9c36bfd3"
      define_method(:install) do
        if OS.mac? && Hardware::CPU.arm?
          bin.install "gitaur-darwin-arm64" => "gitaur"
        elsif OS.mac? && Hardware::CPU.intel?
          bin.install "gitaur-darwin-amd64" => "gitaur"
        else
          bin.install "gitaur"
        fi
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/exceptionate/gitaur/releases/download/v0.1.2/gitaur-linux-arm64.tar.gz"
      sha256 "95d44dc1b90c5355921e1abf7b9558ecba3fe92d889e63bd451aed08e770e34f"
      define_method(:install) do
        if OS.mac? && Hardware::CPU.arm?
          bin.install "gitaur-darwin-arm64" => "gitaur"
        elsif OS.mac? && Hardware::CPU.intel?
          bin.install "gitaur-darwin-amd64" => "gitaur"
        else
          bin.install "gitaur"
        fi
      end
    end
  end
end
