# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitaur < Formula
  desc "A simple git utility CLI tool"
  homepage "https://github.com/Exceptionate/gitaur"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/exceptionate/gitaur/releases/download/v0.1.2/gitaur-darwin-amd64.tar.gz"
      sha256 "bdd433872d91d1f50cab22d6c243f1f6e9816e28d15ecfd0828fe49d3822f8d9"

      define_method(:install) do
        if OS.mac? && Hardware::CPU.arm?
          bin.install "gitaur-darwin-arm64" => "gitaur"
        elsif OS.mac? && Hardware::CPU.intel?
          bin.install "gitaur-darwin-amd64" => "gitaur"
        else
          bin.install "gitaur"
        fi
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/exceptionate/gitaur/releases/download/v0.1.2/gitaur-darwin-arm64.tar.gz"
      sha256 "e63892dde96534e8375b22cd950f001901d740e7c09881701afffac1ea30d9fe"

      define_method(:install) do
        if OS.mac? && Hardware::CPU.arm?
          bin.install "gitaur-darwin-arm64" => "gitaur"
        elsif OS.mac? && Hardware::CPU.intel?
          bin.install "gitaur-darwin-amd64" => "gitaur"
        else
          bin.install "gitaur"
        fi
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/exceptionate/gitaur/releases/download/v0.1.2/gitaur-linux-amd64.tar.gz"
      sha256 "3cb4ae3576b8f025dada4d6639476e34f639ea63856735aaae639a2855361393"
      define_method(:install) do
        if OS.mac? && Hardware::CPU.arm?
          bin.install "gitaur-darwin-arm64" => "gitaur"
        elsif OS.mac? && Hardware::CPU.intel?
          bin.install "gitaur-darwin-amd64" => "gitaur"
        else
          bin.install "gitaur"
        fi
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/exceptionate/gitaur/releases/download/v0.1.2/gitaur-linux-arm64.tar.gz"
      sha256 "202e1745a5eba8cc3c6b287909ff155a95844b16eedb891d1c95e27ab5995f08"
      define_method(:install) do
        if OS.mac? && Hardware::CPU.arm?
          bin.install "gitaur-darwin-arm64" => "gitaur"
        elsif OS.mac? && Hardware::CPU.intel?
          bin.install "gitaur-darwin-amd64" => "gitaur"
        else
          bin.install "gitaur"
        fi
      end
    end
  end
end
